############################################
#                    NOTE:                 #
#       This file should NOT be modified.  #
#       It only exists due to comments     #
#       getting removed on theme switch    #
#                on the original.          #
############################################

[helpers]
eq_string = ".dotter/helpers/strings.rhai"
# Supported Colorschemes:
# - Catppuccin (Mocha)
# - Oxocarbon
[global]
[global.variables.theming]
colorschemes = ["oxocarbon", "catppuccin"]

# Supported Wallpaper Daemons:
# - swww
# - mpvpaper

# Supported Notification Daemons:
# - dunst
# - mako

#   _____ ____  _      ____  _____   _____  _____ _    _ ______ __  __ ______ 
#   / ____/ __ \| |    / __ \|  __ \ / ____|/ ____| |  | |  ____|  \/  |  ____|
#  | |   | |  | | |   | |  | | |__) | (___ | |    | |__| | |__  | \  / | |__   
#  | |   | |  | | |   | |  | |  _  / \___ \| |    |  __  |  __| | |\/| |  __|  
#  | |___| |__| | |___| |__| | | \ \ ____) | |____| |  | | |____| |  | | |____ 
#   \_____\____/|______\____/|_|  \_\_____/ \_____|_|  |_|______|_|  |_|______|

[colorscheme]
depends = ["catppuccin"]
[colorscheme.variables]
# Should Wezterm follow the above Colorscheme
# or use the one set in it's own config
use-wezterm-colorscheme = "false"

[oxocarbon]
[oxocarbon.variables]
theme-name     = "oxocarbon"
rofi-wallpaper = "~/dotfiles/wallpapers/images/cat_nobara.jpg"

[oxocarbon.variables.colors16]
base00 = "161616"
base01 = "262626"
base02 = "393939"
base03 = "525252"
base04 = "dde1e6"
base05 = "f2f4f8"
base06 = "ffffff"
base07 = "08bdba"
base08 = "3ddbd9"
base09 = "78a9ff"
base0A = "ee5396"
base0B = "33b1ff"
base0C = "ff7eb6"
base0D = "42be65"
base0E = "be95ff"
base0F = "82cfff"

[oxocarbon.files]
# Only load the custom theme if vencord is being used in local.toml
"vencord/settings/oxocarbon-theme.css" = { target = "~/.config/Vencord/settings/quickCss.css", type = "symbolic", if = "(eq dotter.packages.vencord true)" }

[catppuccin]
[catppuccin.variables]
theme-name="catppuccin-mocha"
rofi-wallpaper="~/dotfiles/wallpapers/images/night.jpg"

[catppuccin.variables.colors16]
base00 = "1e1e2e" # base
base01 = "181825" # mantle
base02 = "313244" # surface0
base03 = "45475a" # surface1
base04 = "585b70" # surface2
base05 = "cdd6f4" # text
base06 = "f5e0dc" # rosewater
base07 = "b4befe" # lavender
base08 = "f38ba8" # red
base09 = "fab387" # peach
base0A = "f9e2af" # yellow
base0B = "a6e3a1" # green
base0C = "94e2d5" # teal
base0D = "89b4fa" # blue
base0E = "cba6f7" # mauve
base0F = "f2cdcd" # flamingo

[catppuccin.files]
# Only load the custom theme if vencord is being used in local.toml
"vencord/settings/catppuccin-theme.css" = { target = "~/.config/Vencord/settings/quickCss.css", type = "symbolic", if = "(eq dotter.packages.vencord true)" }

# -----------------------------------------------------------------------------------------

#  _______ ______ _____  __  __ _____ _   _          _      
# |__   __|  ____|  __ \|  \/  |_   _| \ | |   /\   | |     
#    | |  | |__  | |__) | \  / | | | |  \| |  /  \  | |     
#    | |  |  __| |  _  /| |\/| | | | | . ` | / /\ \ | |     
#    | |  | |____| | \ \| |  | |_| |_| |\  |/ ____ \| |____ 
#    |_|  |______|_|  \_\_|  |_|_____|_| \_/_/    \_\______|

[git]
[git.files]
"git/gitconfig" = "~/.gitconfig"
# "git/git_template/hooks/commit-msg" = "/usr/share/git-core/templates/hooks/commit-msg"

[zsh]
[zsh.files]
"zsh/zshrc" = "~/.zshrc"
"zsh/broot" = "~/.config/broot/"
"zsh/themes" = "~/.config/zsh/themes"
# "zsh/plugins" = "~/.config/zsh/plugins"

[starship]
[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"

[zellij]
[zellij.files]
"zellij/" = "~/.config/zellij/"

[gh]
[gh.files]
"gh/" = "~/.config/gh"
"gh-dash/" = "~/.config/gh-dash"

[lazygit]
depends = ["colorscheme"]
[lazygit.files]
"lazygit" = "~/.config/lazygit"

[nvim]
depends = ["colorscheme"]
[nvim.files]
"nvim/" = "~/.config/nvim/"

# -----------------------------------------------------------------------------------------

#  __          __ __     ___               _   _ _____  
#  \ \        / /\\ \   / / |        /\   | \ | |  __ \ 
#   \ \  /\  / /  \\ \_/ /| |       /  \  |  \| | |  | |
#    \ \/  \/ / /\ \\   / | |      / /\ \ | . ` | |  | |
#     \  /\  / ____ \| |  | |____ / ____ \| |\  | |__| |
#      \/  \/_/    \_\_|  |______/_/    \_\_| \_|_____/ 

[hyprland]
[hyprland.files]
"hyprland/" = "~/.config/hypr/"

[swww]
[swww.files]
"wallpapers/gifs/" = "~/.config/wallpapers"
"wallpapers/images/" = "~/.config/wallpapers"
[swww.variables]
wallpaper_manager = "swww"

[hyprpaper]
[hyprpaper.files]
"hyprland/hyprpaper.conf" = "~/.config/hypr/hyprpaper.conf"
# swww can just be used instead.
# "wallpapers/images/" = "~/.config/wallpapers"
[hyprpaper.variables]
wallpaper_manager = "hyprpaper"

[mpvpaper]
[mpvpaper.files]
"wallpapers/videos/" = "~/.config/wallpapers"
[mpvpaper.variables]
wallpaper_manager = "mpvpaper"

[mako]
depends = ["colorscheme"]
[mako.files]
"mako/" = "~/.config/mako/"
[mako.variables]
noti_manager = "mako"

# Credits to @SimplyVoid on GitHub for the base Waybar config
[waybar]
depends = ["colorscheme", "hyprland"]
[waybar.files]
"waybar/" = "~/.config/waybar"

# -----------------------------------------------------------------------------------------

#  __  __ _____  _____  _____ 
# |  \/  |_   _|/ ____|/ ____|
# | \  / | | | | (___ | |     
# | |\/| | | |  \___ \| |     
# | |  | |_| |_ ____) | |____ 
# |_|  |_|_____|_____/ \_____|

[dunst]
[dunst.files]
"dunst/" = "~/.config/dunst/"
[dunst.variables]
noti_manager = "dunst"

[imwheel]
[imwheel.files]
"imwheel/imwheelrc" = "~/.imwheelrc"

# [copyq]
# [copyq.files]
# "copyq/" = "~/copyq/"

[scripts]
depends = ["global"]
[scripts.files]
"scripts/" = "~/.config/scripts"
# NOTE: This script requires: tomlq, jq (indirectly), and yj
"scripts/colorscheme_switcher.sh" = { target = "~/.config/scripts/colorscheme_switcher.sh", type = "template" }

# -----------------------------------------------------------------------------------------

#            _____  _____  _      _____ _____       _______ _____ ____  _   _  _____ 
#      /\   |  __ \|  __ \| |    |_   _/ ____|   /\|__   __|_   _/ __ \| \ | |/ ____|
#     /  \  | |__) | |__) | |      | || |       /  \  | |    | || |  | |  \| | (___  
#    / /\ \ |  ___/|  ___/| |      | || |      / /\ \ | |    | || |  | | . ` |\___ \ 
#   / ____ \| |    | |    | |____ _| || |____ / ____ \| |   _| || |__| | |\  |____) |
#  /_/    \_\_|    |_|    |______|_____\_____/_/    \_\_|  |_____\____/|_| \_|_____/ 

[vencord]
[vencord.files]
"vencord" = { target = "~/.config/Vencord/", type = "symbolic" }

[wezterm]
depends = ["colorscheme"]
[wezterm.files]
"wezterm/" = "~/.config/wezterm"

[rofi]
depends = ["colorscheme"]
[rofi.files]
"rofi/" = "~/.config/rofi"

# Fonts
[fonts]
[fonts.files]
"fonts/config" = "~/.config/fontconfig/conf.d/"
