[helpers]
eq_string = ".dotter/helpers/strings.rhai"
arr_inc = ".dotter/helpers/array_includes.rhai"
rgb_f_hx = ".dotter/helpers/hex_csv_rgb.rhai"
hyprland_border_color = ".dotter/helpers/hyprland_border_color.rhai"

[global]
[global.variables]
[global.variables.theming]
colorschemes = ["oxocarbon", "catppuccin", "gruvbox"]

[colorscheme]
depends = ["catppuccin"]
[colorscheme.variables]
use-native-colorscheme = "false"
use-eww-bar = "false"
overrides = []

[oxocarbon]
[oxocarbon.variables]
theme-name = "oxocarbon"
rofi-wallpaper = "~/dotfiles/wallpapers/images/cat_nobara.jpg"
default_wallpaper = "~/dotfiles/wallpapers/images/oxocarbon-painting.jpg"
[oxocarbon.variables.colors16]
base00 = "161616"
base01 = "262626"
base02 = "393939"
base03 = "525252"
base04 = "dde1e6"
base05 = "f2f4f8"
base06 = "ffffff"
base07 = "08bdba"
base08 = "3ddbd9"
base09 = "78a9ff"
base0A = "ee5396"
base0B = "33b1ff"
base0C = "ff7eb6"
base0D = "42be65"
base0E = "be95ff"
base0F = "82cfff"
[oxocarbon.files]
[oxocarbon.files."vencord/settings/oxocarbon-theme.css"]
target = "~/.config/Vencord/settings/quickCss.css"
type = "symbolic"
if = "(eq dotter.packages.vencord true)"

[catppuccin]
[catppuccin.variables]
theme-name = "catppuccin-mocha"
rofi-wallpaper = "~/dotfiles/wallpapers/images/night.jpg"
default_wallpaper = "~/dotfiles/wallpapers/images/mocha-painting.jpg"
[catppuccin.variables.colors16]
base00 = "1e1e2e"
base01 = "181825"
base02 = "313244"
base03 = "45475a"
base04 = "585b70"
base05 = "cdd6f4"
base06 = "f5e0dc"
base07 = "b4befe"
base08 = "f38ba8"
base09 = "fab387"
base0A = "f9e2af"
base0B = "a6e3a1"
base0C = "94e2d5"
base0D = "89b4fa"
base0E = "cba6f7"
base0F = "f2cdcd"
[catppuccin.files]
[catppuccin.files."vencord/settings/catppuccin-theme.css"]
target = "~/.config/Vencord/settings/quickCss.css"
type = "symbolic"
if = "(eq dotter.packages.vencord true)"

[gruvbox]
[gruvbox.variables]
theme-name = "gruvbox"
rofi-wallpaper = "~/dotfiles/wallpapers/images/gruvbox-rust-book.png"
default_wallpaper = "~/dotfiles/wallpapers/images/gruvbox-painting.png"
[gruvbox.variables.colors16]
base00 = "202020"
base01 = "2a2827"
base02 = "504945"
base03 = "5a524c"
base04 = "bdae93"
base05 = "ddc7a1"
base06 = "ebdbb2"
base07 = "fbf1c7"
base08 = "ea6962"
base09 = "e78a4e"
base0A = "d8a657"
base0B = "a9b665"
base0C = "89b482"
base0D = "7daea3"
base0E = "d3869b"
base0F = "bd6f3e"
[gruvbox.files]
[gruvbox.files."vencord/settings/gruvbox-theme.css"]
target = "~/.config/Vencord/settings/quickCss.css"
type = "symbolic"
if = "(eq dotter.packages.vencord true)"

[git]
[git.files]
"git/gitconfig" = "~/.gitconfig"

[zsh]
[zsh.files]
"zsh/zshrc" = "~/.zshrc"
"zsh/themes" = "~/.config/zsh/themes"

[starship]
[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"

[zellij]
[zellij.files]
"zellij/" = "~/.config/zellij/"

[gh]
[gh.files]
"gh/" = "~/.config/gh"
"gh-dash/" = "~/.config/gh-dash"

[lazygit]
depends = ["colorscheme"]
[lazygit.files]
lazygit = "~/.config/lazygit"

[nvim]
depends = ["colorscheme"]
[nvim.files]
"nvim/" = "~/.config/nvim/"

[emacs]

[hyprland]
[hyprland.files]
"hyprland/" = "~/.config/hypr/"
[hyprland.variables]
gaps-out = 20
border-color-active = "6d6956ff"
border-color-inactive = "6d695620"

[swww]
[swww.files]
"wallpapers/gifs/" = "~/.config/wallpapers"
"wallpapers/images/" = "~/.config/wallpapers"
[swww.variables]
wallpaper_manager = "swww"

[hyprpaper]
[hyprpaper.files]
"hyprland/hyprpaper.conf" = "~/.config/hypr/hyprpaper.conf"
[hyprpaper.variables]
wallpaper_manager = "hyprpaper"

[mpvpaper]
[mpvpaper.files]
"wallpapers/videos/" = "~/.config/wallpapers"
[mpvpaper.variables]
wallpaper_manager = "mpvpaper"

[mako]
depends = ["colorscheme"]
[mako.files]
"mako/" = "~/.config/mako/"
[mako.variables]
noti_manager = "mako"

[waybar]
depends = ["colorscheme", "hyprland"]
[waybar.files]
"waybar/" = "~/.config/waybar"

[eww]
[eww.files]
"eww/" = "~/.config/eww/"

[dunst]
[dunst.files]
"dunst/" = "~/.config/dunst/"
[dunst.variables]
noti_manager = "dunst"

[imwheel]
[imwheel.files]
"imwheel/imwheelrc" = "~/.imwheelrc"

[scripts]
depends = ["global"]
[scripts.files]
"scripts/" = "~/.config/scripts"
[scripts.files."scripts/colorscheme_switcher.sh"]
target = "~/.config/scripts/colorscheme_switcher.sh"
type = "template"

[vencord]
[vencord.files]
[vencord.files.vencord]
target = "~/.config/Vencord/"
type = "symbolic"

[wezterm]
depends = ["colorscheme"]
[wezterm.files]
"wezterm/" = "~/.config/wezterm"

[jerry]
[jerry.files]
"jerry/" = "~/.config/jerry/"

[rofi]
depends = ["colorscheme"]
[rofi.files]
"rofi/" = "~/.config/rofi"

[fonts]
[fonts.files]
"fonts/config" = "~/.config/fontconfig/conf.d/"
