autoload -U +X compinit && compinit
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=/var/lib/flatpak/exports/bin/:/$HOME/.local/bin/:$PATH
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CONFIG_HOME=$HOME/.config

# History
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=$HOME/.cache/zsh/history

# Env vars
export EDITOR=nvim

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="catppuccin-mocha"

# Plugins
source ~/dotfiles/zsh/functions/githubclone
autoload -Uz ghcl
source ~/dotfiles/zsh/themes/catppuccin-highlight/themes/catppuccin_mocha-zsh-syntax-highlighting.zsh
autoload -Uz transfer
source ~/dotfiles/zsh/plugins/fzf-tab/fzf-tab.plugin.zsh
source ~/dotfiles/zsh/plugins/zsh-exa-alias.zsh
source ~/dotfiles/zsh/plugins/git.plugin.zsh
source ~/dotfiles/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
fpath=(
    /usr/share/zsh/functions
  "${fpath[@]}"
)

# User configuration
alias cat=bat

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

# Easier CD (i.e. cd dots -> dots)
setopt autocd
# CTRL+Backspace
bindkey ^H backward-delete-word
bindkey ^R history-incremental-search-backward
bindkey '^[[A' up-line-or-search

source ./.fzf.zsh

# Oxocarbon fzf
{{ #if (eq_string theme-name "oxocarbon") }}
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS' --color=fg:#ffffff,bg:-1,hl:#08bdba --color=fg+:#f2f4f8,bg+:-1,hl+:#3ddbd9 --color=info:#78a9ff,prompt:#33b1ff,pointer:#42be65 --color=marker:#ee5396,spinner:#ff7eb6,header:#be95ff
  --reverse --border=rounded '
{{ /if }}
{{ #if (eq_string theme-name "catppuccin-mocha") }}
export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 --border=rounded"
{{ /if }}
